name: gettest
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  dio: ^5.6.0
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.2
  formz: ^0.7.0
  get_it: ^7.7.0
  go_router: ^14.2.3
  image_picker: ^1.1.2
  internet_connection_checker: ^2.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  keyboard_dismisser: ^3.0.0
  logger: ^2.4.0
  mask_text_input_formatter: ^2.9.0
  mobile_scanner: ^5.2.1
  myid: ^1.2.5
  path: ^1.9.0
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
