name: gettest
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  keyboard_dismisser: ^3.0.0
  equatable: ^2.0.5
  connectivity_plus: ^6.1.0
  internet_connection_checker: ^1.0.0+1
  formz: ^0.7.0
  dio: ^5.7.0
  get_it: ^8.0.0
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  path: ^1.9.0
  device_info_plus: ^11.1.0
  flutter_animate: ^4.5.0
  logger: ^2.4.0
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  flutter_spinkit: ^5.2.1
  myid: ^1.2.6
  uuid: ^4.5.1
  image_picker: ^1.1.2
  flutter_widget_from_html: ^0.15.2
  pinput: ^5.0.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  # mobile_scanner: ^6.0.1
  # firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
