// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6GiSuQtDergP9XmYgOwUJamYzDNYrTXk',
    appId: '1:433161509720:web:5a9210572437c191eca32d',
    messagingSenderId: '433161509720',
    projectId: 'gettest-c74a7',
    authDomain: 'gettest-c74a7.firebaseapp.com',
    storageBucket: 'gettest-c74a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAR0_gspGv5QoIidD-0vM-XMNMZ4Xo_2w',
    appId: '1:433161509720:android:1f90904d86e657cdeca32d',
    messagingSenderId: '433161509720',
    projectId: 'gettest-c74a7',
    storageBucket: 'gettest-c74a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDtVt5nW4xLdeTnCygnsuPa5a1iJS6tYs',
    appId: '1:433161509720:ios:65eee321f35224ececa32d',
    messagingSenderId: '433161509720',
    projectId: 'gettest-c74a7',
    storageBucket: 'gettest-c74a7.appspot.com',
    iosBundleId: 'com.gettest.gettest',
  );

}